# Generated by Django 5.2.6 on 2025-09-21 18:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aktualita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nadpis', models.CharField(max_length=255, verbose_name='Nadpis')),
                ('obsah', models.TextField(verbose_name='Obsah článku')),
                ('obrazek', models.ImageField(blank=True, null=True, upload_to='aktuality/', verbose_name='Hlavní obrázek')),
                ('datum_vytvoreni', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum vytvoření')),
                ('zverejneno', models.BooleanField(default=True, verbose_name='Zveřejněno?')),
            ],
            options={
                'verbose_name': 'Aktualita',
                'verbose_name_plural': 'Aktuality',
                'ordering': ['-datum_vytvoreni'],
            },
        ),
        migrations.CreateModel(
            name='KategorieMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, unique=True, verbose_name='Název kategorie')),
                ('poradi', models.PositiveIntegerField(default=0, help_text='Pro seřazení kategorií na webu.')),
            ],
            options={
                'verbose_name': 'Kategorie menu',
                'verbose_name_plural': 'Kategorie menu',
                'ordering': ['poradi'],
            },
        ),
        migrations.CreateModel(
            name='PolozkaMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200, verbose_name='Název položky')),
                ('popis', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cena v Kč')),
                ('alergeny', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alergeny (čísla)')),
                ('obrazek', models.ImageField(blank=True, null=True, upload_to='menu_obrazky/', verbose_name='Obrázek jídla')),
                ('dostupne', models.BooleanField(default=True, verbose_name='Je dostupné?')),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozky', to='web.kategoriemenu', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Položka menu',
                'verbose_name_plural': 'Položky menu',
                'ordering': ['kategorie__poradi', 'nazev'],
            },
        ),
    ]
